version: '3.5'

services:
  # frontend:
  #   container_name: moneysens_frontend
  #   image: moneysense/frontend
  #   build:
  #     dockerfile: ./front/Dockerfile
  #   depends_on:
  #     - backend
  #   ports:
  #     - "3000:80"
  #   networks:
  #     - moneysense_network
  db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
    container_name: postgres
    volumes:
      - /volumes/pgdata
    ports:
      - '5432:5432'
    networks:
      - moneysense_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - .:/usr/src/app
    networks:
      - moneysense_network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    container_name: nest-pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=pgadmin4
    ports:
      - '5050:80'
    depends_on:
      - db
    networks:
      - moneysense_network
networks:
  moneysense_network:
    name: moneysense_network
